sudo: required
language: node_js
node_js:
  - "10"
services:
  - docker

before_install:
  # login to docker registries (dockerhub)
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

install:
  # install deps
  - npm install

script:
  - npm build
  # build docker images
  - docker build -t hardware-eshop .

after_success:
  - docker tag hardware-eshop $DOCKER_USER/hardware-eshop:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/hardware-eshop:$TRAVIS_BUILD_NUMBER
  - docker tag hardware-eshop $DOCKER_USER/hardware-eshop:latest
  - docker push $DOCKER_USER/hardware-eshop:latest